### ISSUE TITLE
Timer should be cancelled in dispose()

### ISSUE THREAD

**Issue by ratherNotB** [ThomasEcalle/delayed_display#1]
First off, thanks for making this widget... it's great!

I noticed the following issue when changing routes while the timer is still running:

AnimationController.forward() called after AnimationController.dispose()

It can be resolved by doing the following:

Create a new private variable:

var _timer;

Assign the timer to it:

_timer = Timer(delay, () {
          _opacityController.forward();
        });

Modify the dispose() method as follows:

  /// Dispose the opacity controller
  @override
  void dispose() {
    _opacityController.dispose();
    if (_timer != null) {
      _timer.cancel();
    }
    super.dispose();
  }

**Comment by ThomasEcalle** [comment]
Hi @ratherNotB 

Thank you for your issue that is totally right :)
It has taken me some time to be able to work again on that widget but here we are, a new version 1.0.3 is now uploaded with this change !

Hopping it will help you
